project:
  type: book

book:
  title: "ğŸ  The House Analogy Guide to Quarto & GitHub"
  author: "Julia Schmid"
  date: "2025-05-11"
  chapters:
    - index.qmd
    - intro.qmd
    - setup.qmd
    - summary.qmd
    - start_building.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

output-dir: _site

publish:
  site: gh-pages

