project:
  type: book
  output-dir: docs

book:
  title: "üè† The House Analogy Guide to Quarto & GitHub"
  author: "Julia Schmid"
  date: "2025-05-11"
  chapters:
    - index.qmd
    - intro.qmd
    - setup.qmd
    - start_building.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

publish:
  site: gh-pages

