name: Publish Quarto Book

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Render Quarto Project
        run: quarto render

      - name: Move site to docs folder
        run: |
          rm -rf docs
          mv _site docs

      - name: Commit results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs
          git commit -m "Update site" || echo "No changes to commit"

      - name: Push changes
        run: git push
